name: kr_builder
description: A Flutter package that replaces FutureBuilder and StreamBuilder with shimmer and animation effects.
version: 1.0.4
homepage: 'https://github.com/karrarfalih/kr_builder'

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
