name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Activate dart packages
        run: pub global activate dartdoc
      - name: Build and publish package
        run: |
          pub get
          dartdoc
          pub publish